import fs from 'fs';
import path from 'path';
const JSON_DIR = path.resolve(process.cwd(), 'src/json');
const isNumber = (x) => typeof x === 'number' && !isNaN(x);
export const defaultUserConfig = Object.freeze({
  money: 0,
  exp: 0,
  chat: 0,
  chatTotal: 0,
  limit: 50,
  donasi: 0,
  lastclaim: 0,
  skata: 0,
  pc: 0,
  lastseen: 0,
  pacaranTime: 0,
  registered: false,
  pacar: '',
  tembak: '',
  ditembak: false,
  name: '',
  age: -1,
  regTime: -1,
  afk: -1,
  unreg: false,
  afkReason: '',
  banned: false,
  bannedTime: 0,
  WarnReason: '',
  warning: 0,
  level: 0,
  role: 'Beginner',
  rank: 'Bronze',
  created: Date.now(),
  email: '',
  verif: false,
  command: 0,
  commandTotal: 0,
  commandLimit: 50,
  cmdLimitMsg: 0,
  chip: 0,
  atm: 0,
  fullatm: 0,
  bank: 0,
  health: 100,
  energy: 100,
  sleep: 100,
  potion: 0,
  trash: 0,
  wood: 0,
  rock: 0,
  string: 0,
  petfood: 0,
  emerald: 0,
  diamond: 0,
  gold: 0,
  botol: 0,
  kardus: 0,
  kaleng: 0,
  gelas: 0,
  plastik: 0,
  iron: 0,
  common: 0,
  uncommon: 0,
  mythic: 0,
  legendary: 0,
  umpan: 0,
  pet: 0,
  paus: 0,
  kepiting: 0,
  gurita: 0,
  cumi: 0,
  buntal: 0,
  dory: 0,
  lumba: 0,
  lobster: 0,
  hiu: 0,
  udang: 0,
  orca: 0,
  banteng: 0,
  gajah: 0,
  harimau: 0,
  kambing: 0,
  panda: 0,
  buaya: 0,
  kerbau: 0,
  sapi: 0,
  monyet: 0,
  babihutan: 0,
  babi: 0,
  ayam: 0,
  steak: 0,
  ayamGoreng: 0,
  ribs: 0,
  roti: 0,
  udangGoreng: 0,
  bacon: 0,
  gandum: 0,
  minyak: 0,
  garam: 0,
  ojek: 0,
  polisi: 0,
  roket: 0,
  taxy: 0,
  lockBankCD: 0,
  lasthackbank: 0,
  lastadventure: 0,
  lastkill: 0,
  lastmisi: 0,
  lastdungeon: 0,
  lastwar: 0,
  lastsda: 0,
  lastduel: 0,
  lastmining: 0,
  lasthunt: 0,
  lastgift: 0,
  lastberkebon: 0,
  lastdagang: 0,
  lasthourly: 0,
  lastbansos: 0,
  lastrampok: 0,
  lastnebang: 0,
  lastweekly: 0,
  lastmonthly: 0,
  apel: 0,
  anggur: 0,
  jeruk: 0,
  mangga: 0,
  pisang: 0,
  makanan: 0,
  bibitanggur: 0,
  bibitpisang: 0,
  bibitapel: 0,
  bibitmangga: 0,
  bibitjeruk: 0,
  pets: {
    cat: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    dog: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    horse: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    fox: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    robo: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    lion: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    wolf: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    griffin: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    centaur: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    kyubi: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    phoenix: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
    dragon: {
      level: 0,
      exp: 0,
      last_feed: 0,
    },
  },
  armor: 0,
  armordurability: 0,
  sword: 0,
  sworddurability: 0,
  pickaxe: 0,
  pickaxedurability: 0,
  fishingrod: 0,
  fishingroddurability: 0,
  premium: false,
  autolevelup: false,
  noPrefix: false,
  autodownload: false,
  sticker: {},
  invest: {},
  saham: {},
  task: {},
  historyTrx: [],
  rumah: {},
  premiumTime: 0,
  coin: 0,
  credit: 0,
  lastcoinclaim: 0,
  assistant: 'default',
  assistants: [],
  redeemed: [],
  farm: [],
  quest: {},
  profession: '',
  lastproperti: 0,
  lastojek: 0,
});
const isPlainObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
export function repairUser(user) {
  if (!isPlainObject(user)) return 0;
  let fixed = 0;
  const walk = (obj, def) => {
    for (const [k, d] of Object.entries(def)) {
      const v = obj[k];
      if (Array.isArray(d)) {
        if (!Array.isArray(v)) {
          obj[k] = structuredClone(d);
          fixed++;
        }
        continue;
      }
      if (isPlainObject(d)) {
        if (!isPlainObject(v)) {
          obj[k] = structuredClone(d);
          fixed++;
        } else walk(v, d);
        continue;
      }
      const ok = typeof d === 'number' ? typeof v === 'number' && !isNaN(v) : typeof v === typeof d;
      if (!ok) {
        obj[k] = structuredClone(d);
        fixed++;
      }
    }
  };
  walk(user, defaultUserConfig);
  return fixed;
}
export const defaultChatConfig = Object.freeze({
  isBanned: false,
  isBannedTime: false,
  mute: false,
  adminOnly: false,
  antiBot: false,
  welcome: false,
  detect: false,
  sWelcome: '',
  sBye: '',
  sPromote: '',
  sDemote: '',
  otakuNews: false,
  otakuNow: '',
  komikuNews: false,
  komikuNow: '',
  antidelete: false,
  antiLinks: false,
  antiLinkGc: false,
  antiLinkCh: false,
  antiVn: false,
  antiSticker: false,
  antiToxic: false,
  antiVirtex: false,
  antiBadword: false,
  antiPromosi: false,
  antiPromosiText: false,
  antiNsfw: false,
  pembatasan: false,
  nodelete: false,
  viewonce: false,
  simi: false,
  nsfw: false,
  rpg: true,
  game: true,
  teks: true,
  notifgempa: false,
  gempaDateTime: '',
  autolevelup: false,
  autodownload: false,
  warnLimit: 3,
  expired: 0,
  store: {},
  member: {},
  banFitur: [],
});
export const defaultSettingsConfig = Object.freeze({
  self: false,
  autoread: true,
  autoRestock: false,
  autobio: true,
  button: false,
  composing: false,
  restrict: true,
  autorestart: true,
  backup: false,
  cleartmp: false,
  anticall: true,
  adReply: false,
  typeText: 0,
  noerror: false,
  didYouMean: false,
});
export const defaultBotConfig = Object.freeze({
  replyText: {},
  rating: {},
  users: {},
  menfess: {},
  anonymous: {},
  absen: {},
  logs: {},
  ultah: {},
  gempaDateTime: '',
  otakuNow: '',
  komikuNow: '',
  sellRumah: {},
  invest: JSON.parse(fs.readFileSync(`${JSON_DIR}/crypto.json`, 'utf8')),
  stock: JSON.parse(fs.readFileSync(`${JSON_DIR}/stock.json`, 'utf-8')),
  saham: JSON.parse(fs.readFileSync(`${JSON_DIR}/saham.json`, 'utf-8')),
  rumah: JSON.parse(fs.readFileSync(`${JSON_DIR}/rumah.json`, 'utf-8')),
  jadwalsholat: JSON.parse(fs.readFileSync(`${JSON_DIR}/jadwalsholat.json`, 'utf-8')),
});
export const defaultMemberConfig = Object.freeze({
  warn: 0,
  blacklist: false,
  banned: false,
  bannedTime: 0,
  chat: 0,
  chatTotal: 0,
  command: 0,
  commandTotal: 0,
  lastseen: 0,
});
